      SUBROUTINE SYSTEM(LINE)
C	Added IMPLCIT NONE TR July 2000
      IMPLICIT NONE
      CHARACTER LINE*(*)
      INTEGER ISTAT_DCL
      INTEGER LIB$SPAWN

      ISTAT_DCL = LIB$SPAWN (LINE(1:255)) ! Don't overflow.
      IF (.NOT. ISTAT_DCL) CALL LIB$STOP (%VAL(ISTAT_DCL))
      RETURN
      END
