	SUBROUTINE LSQ_FIT (NPT, XDAT, DXDAT, YDAT, DYDAT, 
     >		Y0, DY0, SLOPE, DSLOPE, QUAD, DQUAD, CHISQ)
C-------------------------------------------------------------------
C...Make a quadratic least-squares fit to a collection of 
C   NPT points (XDAT,DXDAT,YDAT,DYDAT) and return their 
C   zero-intercept, slope and quadratic coefficient with errors. 
C	  POINTS WITH ZERO ERRORS ARE IGNORED!
C
C...Also, as of 13 Aug 85, DXDAT errors are ignored. 	-- Jess Brewer
C-------------------------------------------------------------------
	REAL*4 XDAT(1), DXDAT(1), YDAT(1), DYDAT(1)
	REAL*4 AAA(3,3), BBB(3), WKAREA(10)
C===================================================================
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C	WRITE (*,1764) NPT
C 1764	FORMAT (/,' LSQFIT called with',I4,' points (X,Y,dY):',/)
C	DO 2976 I=1,NPT
C	WRITE (*,7698) XDAT(I), DXDAT(I), YDAT(I), DYDAT(I)
C 7698	FORMAT (1X,4G15.5)
C 2976	CONTINUE
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
	CHISQ = 0.0
	Y0 = 0.0
	DY0 = 0.0
	SLOPE = 0.0
	DSLOPE = 0.0
	QUAD = 0.0
	DQUAD = 0.0
	IF (NPT .EQ. 0) RETURN
	IF (NPT .EQ. 1) THEN
		Y0 = YDAT(1)
		DY0 = DYDAT(1)
		RETURN
	ELSE IF (NPT .EQ. 2) THEN
		CALL LIN_FIT (NPT, XDAT, DXDAT, YDAT, DYDAT, 
     >			Y0, DY0, SLOPE, DSLOPE, CHISQ)
		RETURN
	END IF
C
C...WEIGHTED fit:
C
	SUMW = 0.0
	SUMX = 0.0
	SUMX2 = 0.0
	SUMX3 = 0.0
	SUMX4 = 0.0
	SUMY = 0.0
	SUMYX = 0.0
	SUMYX2 = 0.0
	SUMYX3 = 0.0
	ANNN = 0.0
C
	DO 2050 I=1,NPT
	WT = DYDAT(I)
	IF (WT .EQ. 0.0) GO TO 2050
	ANNN = ANNN + 1.0
	WT = 1.0/(WT*WT)
	X = XDAT(I)
	X2W = X*X*WT
	X3W = X*X2W
	YW = YDAT(I)*WT
	YXW = YW*X
	YX2W = YXW*X
	SUMW = SUMW + WT
	SUMX = SUMX + X*WT
	SUMX2 = SUMX2 + X2W
	SUMX3 = SUMX3 + X3W
	SUMX4 = SUMX4 + X3W*X
	SUMY = SUMY + YW
	SUMYX = SUMYX + YXW
	SUMYX2 = SUMYX2 + YX2W
	SUMYX3 = SUMYX3 + YX2W*X
 2050	CONTINUE
C
	IF (ANNN .EQ. 0.0) RETURN
C
	AVGW = SUMW/ANNN
	AVGX = SUMX/ANNN
	AVGX2 = SUMX2/ANNN
	AVGX3 = SUMX3/ANNN
	AVGX4 = SUMX4/ANNN
	AVGY = SUMY/ANNN
	AVGYX = SUMYX/ANNN
	AVGYX2 = SUMYX2/ANNN
	AVGYX3 = SUMYX3/ANNN
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C	AVX = AVGX/AVGW
C	AVX2 = AVGX2/AVGW
C	AVX3 = AVGX3/AVGW
C	AVX4 = AVGX4/AVGW
C	AVY = AVGY/AVGW
C	AVYX = AVGYX/AVGW
C	AVYX2 = AVGYX2/AVGW
C	AVYX3 = AVGYX3/AVGW
C	WRITE (*,9769) AVGW,AVX,AVX2,AVX3,AVX4,
C     >			AVY,AVYX,AVYX2,AVYX3
C 9769	FORMAT (1X,'Average W, X,X2,X3,X4, Y,YX,YX2,YX3:',/,
C     >		1X,G15.5,/,1X,4G15.5,/,1X,4G15.5)
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C
	AAA(1,1) = AVGW
	AAA(1,2) = AVGX
	AAA(1,3) = AVGX2
	AAA(2,1) = AVGX
	AAA(2,2) = AVGX2
	AAA(2,3) = AVGX3
	AAA(3,1) = AVGX2
	AAA(3,2) = AVGX3
	AAA(3,3) = AVGX4
C
	BBB(1) = AVGY
	BBB(2) = AVGYX
	BBB(3) = AVGYX2
C
	CALL LEQT1F (AAA, 1, 3, 3, BBB, 0, WKAREA, IERR)
C
	IF (IERR .EQ. 129) WRITE (*,9999)
 9999	FORMAT (/,' *** LSQ_FIT: LEQT1F cannot solve matrix! ',/)
C
	Y0 = BBB(1)
	SLOPE = BBB(2)
	QUAD = BBB(3)
C
C	QQQ = AVGX2*(AVGW - 1.0)
C	RRR = (AVGX3 - AVGX*AVGX2/AVGW)/QQQ
C	QUAD = (AVGYX2 - RRR*(AVGYX - AVGY*AVGX))/
C     >	 (AVGX4 - AVGX2*AVGX2/AVGW - 
C     >		  RRR*(AVGX3 - AVGX*AVGX2)) 
C	SLOPE = (AVGYX - AVGY*AVGX + 
C     >		     QUAD*(AVGX*AVGX2 - AVGX3))/QQQ
C	Y0 = (AVGY - SLOPE*AVGX - QUAD*AVGX2)/AVGW
C
	DY0 = 1.0/SQRT(2.0*SUMW)
	DSLOPE = 1.0/SQRT(2.0*SUMX2)
	DQUAD = 1.0/SQRT(2.0*SUMX4)
C
C...Now find chisquared: 
C
	CHISQ = 0.
	DO 200 I=1,NPT
	IF (DYDAT(I) .EQ. 0.) GO TO 200
	X = XDAT(I)
	WT = DYDAT(I)*DYDAT(I)
	CHISQ = CHISQ + 
     >		(Y0 + SLOPE*X + QUAD*X*X - YDAT(I))**2/WT
  200	CONTINUE
C
	RETURN
	END
