      SUBROUTINE ORDER (INCDEC, NSI, NTERMS, SET, ASET, BSET, CSET) 
C 
C  ORDER THE NSETS ARRAYS SET, ASET, ... IN INCREASING (INCDEC .GT. 0) 
C  OR DECREASING (INCDEC .LT. 0) ORDER OF THE ELEMENTS OF SET.  THAT IS, 
C  THE ORDER OF SET(I) VALUES DETERMINES THE ORDER OF THE OTHER ARRAYS, 
C  MAINTAINING THE ORIGINAL ASSOCIATIONS OF ELEMENTS. 
C  NSETS MAY NOT BE GREATER THAN 4 AS WRITTEN.  THE SUBROUTINE MAY NOT BE 
C  CALLED WITH LESS THAN 7 ARGUMENTS, E.G. CALL ORDER (1, 1, N, SET). 
C  SO IF YOU WANT TO HAVE ONLY ONE SATTELITE SET, SPECIFY IT SEVERAL TIMES.
C  IBM FORTRAN BEING WHAT IT IS, YOU MAY NOT TRY TO ORDER ANY INTEGER SETS,
C  EVEN THE SATTELITE SETS.  ALL THE SETS MUST BE REAL*4 IN MAIN PROGRAM.
C 
      DIMENSION SET(*), ASET(*), BSET(*), CSET(*) 
C 
      IF (NTERMS .LT. 2) RETURN 
      NSETS = MIN(MAX(1,NSI),4) 
      DO 200 N=2,NTERMS 
      DO 300 I=1,N 
      TESTI = SET(I)
      TESTN = SET(N)
      IF (INCDEC .GT. 0) GO TO 1000 
C  DECREASING ORDER. 
      IF (TESTI .GE. TESTN) GO TO 300 
      GO TO 1001 
C  INCREASING ORDER. 
 1000 IF (TESTI .LE. TESTN) GO TO 300 
 1001 TEMP = SET(N) 
      IF (NSETS .LT. 2) GO TO 10 
      TEMPA = ASET(N) 
      IF (NSETS .LT. 3) GO TO 10 
      TEMPB = BSET(N) 
      IF (NSETS .LT. 4) GO TO 10 
      TEMPC = CSET(N) 
   10 DO 400 J=I,N 
      M = N - J + I 
      IF (M .LE. 1) GO TO 400 
      SET(M) = SET(M-1) 
      IF (NSETS .LT. 2) GO TO 400 
      ASET(M) = ASET(M-1) 
      IF (NSETS .LT. 3) GO TO 400 
      BSET(M) = BSET(M-1) 
      IF (NSETS .LT. 4) GO TO 400 
      CSET(M) = CSET(M-1) 
  400 CONTINUE 
      SET(I) = TEMP 
      IF (NSETS .LT. 2) GO TO 200 
      ASET(I) = TEMPA 
      IF (NSETS .LT. 3) GO TO 200 
      BSET(I) = TEMPB 
      IF (NSETS .LT. 4) GO TO 200 
      CSET(I) = TEMPC 
      GO TO 200 
  300 CONTINUE 
  200 CONTINUE 
      RETURN 
      END 
