C...WTDAVG...
C
C...A SUBROUTINE TO RETURN THE PROPERLY WEIGHTED AVERAGE
C   OF A LIST OF SUPPOSEDLY EQUIVALENT MEASUREMENTS AND
C   THEIR ERRORS.POINTS WITH ZERO ERRORS ARE IGNORED!
C
	SUBROUTINE WTDAVG (N, X, DX, XAVG, DXAVG, S)
C
	DIMENSION X(1), DX(1)
C
C
C
	XAVG = X(1)
	DXAVG = DX(1)
	IF (N .LT. 2) RETURN
C
	WSUM = 0.
	ESUM = 0.
	NN = N
	DO 100 I=1,N
	IF (DX(I) .NE. 0.) GO TO 90
	NN = NN - 1
	GO TO 100
   90 EE = 1.0/(DX(I)*DX(I))
	ESUM = ESUM + EE
	WSUM = WSUM + EE*X(I)
  100 CONTINUE
	DXAVG = 1.0/SQRT(ESUM)
	XAVG = WSUM/ESUM
C...NOW FIND CHISQUARED AND CHECK FOR STDDEV TROUBLE...
	S = 0.
	DO 200 I=1,N
	IF (DX(I) .EQ. 0.) GO TO 200
	S = S + (XAVG-X(I))**2/(DX(I)*DX(I))
  200 CONTINUE
	S = SQRT(S)
	IF (NN .LT. 2) RETURN
	S = S/SQRT(FLOAT(NN-1))
C
	IF (S .GT. 1.) DXAVG = DXAVG*S
C
	RETURN
	END
